branches:
  only:
  - main
language: python
install:
- pip install -r requirements.txt
script:
- python3 -m pytest -v tests/test_dice.py
deploy:
  provider: heroku
  api_key:
    secure: o6gCckSv1l0rwl/pkXg7foGcGOsR1tTV7GK7NOHdkWFWlrpJgwtzYVkP1M1gfV66RJVIDrYU3VCJwlK05a+KTRT0pNUXpz1kddfTg9N7XZCKaxfzm4JYivrkH7VKNYnLSYqLiwZMQU9m18HklwDDk3Oq4cK3qTNWC6J4yEtJxJHuaC7aKz6J4/KvFMAMJ9qxuyTFsIVI/tr6rQaHSX70303aX1pEQ6M16FCh+kOSZvsA5bCWdi5DAO1yXK/JmnUqL8nTeY7niiIO/14nLiRrlVfwDPIkZj85xsbVMb1pRpA+lqgfwtIHmu8UQiWQeyqrRktekADUJVlf/V8xq6RumXmbCoOSJI2X3L7a+Z+ylNKH0fPzBfgyey7aQUUyaUTV9PxrJkdcnENcVLCejz+SjFGhbyqar+eDvyaaVqWRXJnVDUEg8MWmRIhuNdawoGhl2NGx23eGIQoUXW9IqgC6b3T9UVaFNOse0cIWIUUHubivYxXBlQ1T3mJoUgOp4k43Nabfhn0BaDVyakuKDni2JeXlA3L9jsuLbUWndwTivJxhCkV/1lnXlAkBGywsa6ZXhU8kM3m2L5spXtFty9zuFef4SRgW9ZerdC5IVGufDXVKQkIo3ZS6+KToM/jdZPFPtFIOSp5M3XJ5lDLZ01xnVGkYzD/xBbg7EJipsEZgoZ4=
  app:
    main: ci-me-dice-staging
notifications:
  slack:
    secure: robSGiduY+FXUKZ34F/k7o2b5FTfJmcCwdfJIT18MVBRUhRLiKeBFENJYpAwG+3uklSE1Oep0Inbs9jWIrzLbVpEbjeIqhGSDirsFbhwjpyhimoBGwRKmJJqx7g0cRITwSo2UgKn4qTF4hN0xYr5HVvmQhjznOlrze/Rsm2lKonEKI82nvNwLUV/+8sG8kmwKbMuqj0N6mO80jJ/cCyxIC5kNZ1N+bMCYVqKpCOUJDFdqvM/HCLTJcXw7VwkM2nPdhM1Oq+XyEZ/1/XD2/a/F4hAq9K1bQXac35pXxGtppgjplkDLjduMtc+dCkwBUuyN1xKVfqUAg7VlEzUbBrwRUd3N+T3eRx4Zu1QFhMQ2ygOpMmVOjY7x4IvwdSc6KOLKGr5RY9nLpWuhi78DSkBVTYsRbFVJ8sr0WNdYBXgKE+ZT0DcvYD6hfY2o2H1yvnJDU2C1naxUb6CJK8zwvE88zCMMUuDfbEQQ074ZRSi4xzdTPq5Kw93OMHYPMPg+fw3w00tS4JHjXy72v/BYxjn07pM796x7LjUTuVamulziPVebWvyBVba2OFKjFQZbrMu6VvXc1RKdSxUvD6W4JhyyyfE2Nm2YTDkqUJ64gZ1Zot7lBO/BdfhN9vbzALkIyEwmCqgiY5qXqMj4oM83+Ni0TMlK2CNqdvgnA9JQ9cX1ws=
